### ISSUE TITLE
Have options for formatting frontmatter

### ISSUE THREAD

**Issue by wiktoriavh** [cristianvasquez/obsidian-prettify#51]
Currently, when I have frontmatter it will be prettified into this
```yaml
---
aliases:
  - test
tags:
  - test
cssclass:
  - test
---
```
But instead I want it to be inside an array, the way I type it:
```yaml
---
aliases: [test]
tags: [test]
cssclass: [test]
---
```

Would love to have that feature added!
