### ISSUE TITLE
Hashtag janitor pulls shebangs from code blocks into front matter tags

### ISSUE THREAD

**Issue by meangrape** [cristianvasquez/obsidian-prettify#92]
In a note with a code block starting like so
`#!/usr/bin/env bash` and having YAML front matter containing something like
```yaml
---
date created: '2022-01-11'
tags:
  - git
  - '#code'
---
```
running `Markdown prettifier: Run with Hashtag janitor` results in
```yaml
---
date created: '2022-01-11'
tags:
  - git
  - '#code'
  - '#!/usr/bin/env'
date updated: '2022-01-11'
---
```
Is there any way for the janitor to skip code blocks?
